--CREATE USER AND GRAND USER'ACCESS
CREATE ROLE IF NOT EXISTS TPCH_ADMIN;
CREATE ROLE IF NOT EXISTS TPCH_DEVELOPER;
CREATE ROLE IF NOT EXISTS TPCH_ANALYST;
CREATE ROLE IF NOT EXISTS TPCH_VIEWER;

--CHECK 
SHOW ROLES;
-- DROP ROLE !
--REVOKE VÀ GRANT : REVOKE- THU HỒI VÀ GRANT LÀ CẤP QUYỀN 

--ADMIN : GET ALL PRIVILEGES 
GRANT ALL PRIVILEGES ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN; --all quyền thao tác db
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ADMIN; --all quyền thao tác với schemas

--DEVELOPER:
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_DEVELOPER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER --load data
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER --analyze
--bronze
GRANT SELECT,INSERT,DELETE, UPDATE 
ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.STAGING TO ROLE TPCH_DEVELOPER 
--silver
GRANT SELECT, UPDATE,INSERT, DELETE
ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_DEVELOPER

--ANALYST: chỉ select  not update/insert
GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.ANALYTICS TO ROLE TPCH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_ANALYST;

GRANT USAGE ON DATABASE TPCH_ANALYTICS_DB TO ROLE TPCH_VIEWER;
GRANT USAGE ON SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA TPCH_ANALYTICS_DB.REPORTS TO ROLE TPCH_VIEWER;


--CẤU TRÚC DATA BASE VÀ ROWS IN EACH TABLE 
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE,
    ROW_COUNT,
    ROUND(BYTES / (1024 * 1024), 2) AS SIZE_MB,
    LAST_ALTERED
FROM TPCH_ANALYTICS_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('STAGING', 'ANALYTICS', 'REPORTS')
ORDER BY TABLE_SCHEMA, TABLE_NAME;


SHOW ROLES LIKE 'TPCH_%';


SHOW STAGES IN SCHEMA TPCH_ANALYTICS_DB.STAGING;

-- 2. Liệt kê các file dữ liệu bên trong Stage
LIST @TPCH_ANALYTICS_DB.STAGING.TCPH_DATA_STAGE;