--PHẦN DATA NÀY ƯU TIÊN CHECK NGHIỆP VỤ HAY GẶP NHẤT: Kiểm tra trùng lặp khóa chính, kiểm tra nghiệp vụ < giá tiền hoặc số lượng k âm> ngày nhận ko thể dứng trc ngày gửi hàng




--PHÂN TÍCH THEO TRẠNG THÁI CỦA ĐƠN HÀNG
SELECT 
    O_ORDERSTATUS,
    O_ORDERSTATUS_DESC,
    COUNT(O_ORDERKEY)       AS TOTAL_ORDERS,
    ROUND(SUM(O_TOTALPRICE),2)      AS TOTAL_AMOUNT,
    ROUND(AVG(O_TOTALPRICE),2)      AS AVG_ORDER_VALUE,
FROM ANALYTICS.ORDERS_SILVER
GROUP BY O_ORDERSTATUS, O_ORDERSTATUS_DESC
ORDER BY TOTAL_ORDERS DESC


--TOP 10 SẢN PHẨM BÁN ĐƯỢC NHIỀU NHẤT THEO SỐ LƯỢNG 
SELECT 
    L_PARTKEY,
    L_PART_NAME,
    L_PART_TYPE,
    SUM(L_QUANTITY)     AS TOTAL_SOLD,
    ROUND(SUM(L_NET_PRICE),2)  AS TOTAL_NET_SALES
FROM ANALYTICS.LINEITEM_SILVER
GROUP BY L_PARTKEY, L_PART_NAME, L_PART_TYPE
ORDER BY TOTAL_SOLD DESC
LIMIT 10
 


--CHECKING DATA 

--1.CHECK TRÙNG LẶP KHÓA CHÍNH
SELECT  
    O_ORDERKEY,
    COUNT(*) AS QUANTITY_ORDERKEY
FROM ANALYTICS.ORDERS_SILVER
GROUP BY O_ORDERKEY
HAVING COUNT(*) > 1

--2. KIỂM TRA KHÁCH HÀNG NÀO CÓ TRÙNG PRIMARY KEY K
SELECT 
    C_CUSTKEY,
    COUNT(*)    AS QUANITY_PRIMARYKEY
FROM ANALYTICS.CUSTOMER_SILVER
GROUP BY C_CUSTKEY
HAVING COUNT(*) > 1;



--ngày nhận ko được nhỏ hơn ngày gửi hàng
SELECT 
    *
FROM ANALYTICS.LINEITEM_SILVER
WHERE L_RECEIPTDATE < L_SHIPDATE


--GIÁ TIỀN KO DC ÂM
SELECT * FROM ANALYTICS.LINEITEM_SILVER
WHERE L_QUANTITY < 0 OR L_DISCOUNT < 0



--3.3 CÁCH TỐI ƯU CHI PHÍ HIỆU NĂNG ĐỠ TỐN CREDITS TROG SNOWFLAKE VỚI CÂU LỆNH EXPLAIN 

--DÙNG ĐỂ ĐỌC TRƯỚC MÀ K TỐN CREDITS -> TABLE SCAN XONG PRUNNING KIỂU WHERE VÀ ĐỌC THEO COLUMNAR ATTRIBUTE
EXPLAIN
SELECT 
    c.C_MKTSEGMENT,
    COUNT(DISTINCT o.O_ORDERKEY) AS TOTAL_ORDERS,
    SUM(l.L_NET_PRICE) AS TOTAL_REVENUE
FROM ANALYTICS.CUSTOMER_SILVER c
JOIN ANALYTICS.ORDERS_SILVER o ON c.C_CUSTKEY = o.O_CUSTKEY
JOIN ANALYTICS.LINEITEM_SILVER l ON o.O_ORDERKEY = l.L_ORDERKEY
GROUP BY c.C_MKTSEGMENT
ORDER BY TOTAL_REVENUE DESC;


SELECT 
    c.C_MKTSEGMENT,
    COUNT(DISTINCT o.O_ORDERKEY) AS TOTAL_ORDERS,
    SUM(l.L_NET_PRICE) AS TOTAL_REVENUE
FROM ANALYTICS.CUSTOMER_SILVER c
JOIN ANALYTICS.ORDERS_SILVER o ON c.C_CUSTKEY = o.O_CUSTKEY
JOIN ANALYTICS.LINEITEM_SILVER l ON o.O_ORDERKEY = l.L_ORDERKEY
GROUP BY c.C_MKTSEGMENT
ORDER BY TOTAL_REVENUE DESC;